# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: kojiro526/pandoc-pack

    working_directory: ~/workspace

    steps:
      - checkout
      - run:
          echo "export FILENAME_TIMESTAMP=$(TZ=Asia/Tokyo date +%Y%m%d-%H%M)" >> $BASH_ENV
      - run:
          command: |
            apt-get update
            apt-get install -yqq curl git
      - run:
          build.sh -f -n -r ./template/reference-part.docx -o witch-contract-design_${FILENAME_TIMESTAMP}.docx -p "--toc --toc-depth=3 --metadata=confidential=CONFIDENTIAL" ./src/
      - run:
          curl https://slack.com/api/files.upload -F token="${SLACK_TOKEN}" -F channels="${SLACK_CHANNEL}" -F title="witch-contract-design ${FILENAME_TIMESTAMP}" -F filename="witch-contract-design_${FILENAME_TIMESTAMP}.docx" -F file=@"$(pwd)/witch-contract-design_${FILENAME_TIMESTAMP}.docx" -F initial_comment="https://github.com/kojiro526/witch-contract-design/commits/$(git rev-parse HEAD)"
      - run:
          name: Move to artifacts
          command: |
            mkdir -p /tmp/artifacts
            mv witch-contract-design_${FILENAME_TIMESTAMP}.docx /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
